DEFAULT_INVESTED_AMOUNT = 0
DEFAULT_FULL_AMOUNT = 0
GOOGLE_TABLE_LINK = 'https://docs.google.com/spreadsheets/d/{spreadsheet_id}'
MAX_LENGTH_PROJECT_NAME = 100
MIN_LENGTH_PROJECT_NAME = 1
MIN_LENGTH_PROJECT_DESCRIPTION = 1
ROW_COUNT = 100
COLUMN_COUNT = 3
